classes:
  Disease:
    annotations:
      annotators: sqlite:obo:mondo
    attributes: {}
    description: A disease is a pathological condition characterized by a disruption
      in normal bodily functions, which may manifest through a variety of symptoms
      and signs. It can arise from genetic, environmental, infectious, or lifestyle
      factors, and can affect any part of the organism, leading to a range of health
      issues. Diseases can be classified into various categories, including acute,
      chronic, communicable, and non-communicable, and they often require specific
      diagnostic and therapeutic approaches for management and treatment.
    id_prefixes:
    - MONDO
    is_a: HealthCondition
    mixins: []
  EnvironmentalCondition:
    annotations:
      annotators: sqlite:obo:peco
      prompt.examples: air pollution, drought, heat wave, heavy metal exposure, salt
        stress, soil salinity
    attributes: {}
    description: The name of an environmental treatment.
    id_prefixes:
    - PECO
    is_a: NamedEntity
    mixins: []
  HealthCondition:
    annotations:
      annotators: sqlite:obo:mondo
    attributes:
      id:
        description: id
        identifier: true
        range: string
        required: true
    description: A condition that affects the health of an organism, including diseases
      and disorders.
    id_prefixes:
    - MONDO
    is_a: NamedEntity
    mixins: []
  Treatment:
    annotations:
      annotators: sqlite:obo:hp
    attributes: {}
    description: ''
    id_prefixes:
    - HP
    is_a: NamedEntity
    mixins: []
  TreatmentMethod:
    annotations:
      annotators: sqlite:obo:maxo
    attributes: {}
    description: A method used to treat a health condition, which may include various
      therapeutic approaches, interventions, or procedures.
    id_prefixes:
    - MAXO
    is_a: NamedEntity
    mixins: []
default_range: string
description: ''
id: https://schemalink.biodata.di.unimi.it/untitled_schema
imports:
- ontogpt:core
- linkml:types
name: untitled_schema
prefixes:
  HP: http://purl.obolibrary.org/obo/hp/hp-international.owl
  MAXO: http://purl.obolibrary.org/obo/maxo.owl
  MONDO: https://purl.obolibrary.org/obo/mondo/mondo-international.owl
  PECO: http://purl.obolibrary.org/obo/peco.owl
  linkml: https://w3id.org/linkml/
  ontogpt: http://w3id.org/ontogpt/
  rdf: https://www.w3.org/1999/02/22-rdf-syntax-ns
title: Untitled schema
