classes:
  Therapy:
    attributes:
      substance_type:
        range: CHEBIDrugs
    is_a: Node
enums:
  CHEBIDrugs:
    reachable_from:
      source_nodes:
      - CHEBI:23888
      source_ontology: obo:chebi
id: https://t/pg-chebi-bad
imports:
- linkml:types
name: pg-chebi-bad
prefixes:
  CHEBI: http://purl.obolibrary.org/obo/CHEBI_
  linkml: https://w3id.org/linkml/
  rdf: https://www.w3.org/1999/02/22-rdf-syntax-ns#
